/********************************************************************************
** Form generated from reading UI file 'lastwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.13.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_LASTWINDOW_H
#define UI_LASTWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDialog>
#include <QtWidgets/QLabel>
#include <QtWidgets/QTextBrowser>

QT_BEGIN_NAMESPACE

class Ui_LastWindow
{
public:
    QTextBrowser *textBrowser;
    QLabel *label_cq;
    QLabel *label_bj;
    QLabel *label_xg;
    QLabel *label_sh;
    QLabel *label_tj;
    QLabel *label_lz;
    QLabel *label_am;
    QLabel *label_by;
    QLabel *label_dh;
    QLabel *label_ts;
    QLabel *label_sjz;
    QLabel *label_zjk;
    QLabel *gs;
    QLabel *cq;
    QLabel *bj;
    QLabel *hb;
    QLabel *hn;
    QLabel *zj;
    QLabel *ah;
    QLabel *hlj;
    QLabel *jl;
    QLabel *ln;
    QLabel *nmg;
    QLabel *xj;
    QLabel *fj;
    QLabel *jx;
    QLabel *sc;
    QLabel *js;
    QLabel *sd;
    QLabel *sh;
    QLabel *tj;
    QLabel *label_zz;
    QLabel *label_kf;
    QLabel *label_ly;
    QLabel *label_jn;
    QLabel *label_qd;
    QLabel *label_yt;
    QLabel *label_rz;
    QLabel *label_nc;
    QLabel *label_jj;
    QLabel *label_sr;
    QLabel *label_gz;
    QLabel *label_cd;
    QLabel *label_zg;
    QLabel *label_my;
    QLabel *label_luzhou;
    QLabel *label_nj;
    QLabel *label_xz;
    QLabel *label_yz;
    QLabel *label_heb;
    QLabel *label_cc;
    QLabel *label_bx;
    QLabel *label_hhht;
    QLabel *label_wlmq;
    QLabel *label_xm;
    QLabel *label_qz;
    QLabel *label_fz;
    QLabel *label_hz;
    QLabel *label_hf;
    QLabel *cityCount;
    QLabel *userRate;
    QLabel *username;
    QLabel *count;
    QLabel *rate;

    void setupUi(QDialog *LastWindow)
    {
        if (LastWindow->objectName().isEmpty())
            LastWindow->setObjectName(QString::fromUtf8("LastWindow"));
        LastWindow->resize(1223, 846);
        textBrowser = new QTextBrowser(LastWindow);
        textBrowser->setObjectName(QString::fromUtf8("textBrowser"));
        textBrowser->setGeometry(QRect(100, 760, 256, 71));
        textBrowser->setStyleSheet(QString::fromUtf8("font: 87 9pt \"Arial\";"));
        label_cq = new QLabel(LastWindow);
        label_cq->setObjectName(QString::fromUtf8("label_cq"));
        label_cq->setGeometry(QRect(680, 530, 61, 21));
        label_bj = new QLabel(LastWindow);
        label_bj->setObjectName(QString::fromUtf8("label_bj"));
        label_bj->setGeometry(QRect(840, 320, 51, 16));
        label_xg = new QLabel(LastWindow);
        label_xg->setObjectName(QString::fromUtf8("label_xg"));
        label_xg->setGeometry(QRect(820, 730, 54, 12));
        label_sh = new QLabel(LastWindow);
        label_sh->setObjectName(QString::fromUtf8("label_sh"));
        label_sh->setGeometry(QRect(905, 515, 51, 21));
        label_tj = new QLabel(LastWindow);
        label_tj->setObjectName(QString::fromUtf8("label_tj"));
        label_tj->setGeometry(QRect(820, 340, 51, 16));
        label_lz = new QLabel(LastWindow);
        label_lz->setObjectName(QString::fromUtf8("label_lz"));
        label_lz->setGeometry(QRect(600, 410, 51, 16));
        label_am = new QLabel(LastWindow);
        label_am->setObjectName(QString::fromUtf8("label_am"));
        label_am->setGeometry(QRect(800, 750, 51, 16));
        label_by = new QLabel(LastWindow);
        label_by->setObjectName(QString::fromUtf8("label_by"));
        label_by->setGeometry(QRect(640, 440, 51, 16));
        label_dh = new QLabel(LastWindow);
        label_dh->setObjectName(QString::fromUtf8("label_dh"));
        label_dh->setGeometry(QRect(480, 330, 51, 16));
        label_ts = new QLabel(LastWindow);
        label_ts->setObjectName(QString::fromUtf8("label_ts"));
        label_ts->setGeometry(QRect(875, 310, 51, 16));
        label_sjz = new QLabel(LastWindow);
        label_sjz->setObjectName(QString::fromUtf8("label_sjz"));
        label_sjz->setGeometry(QRect(810, 290, 51, 16));
        label_zjk = new QLabel(LastWindow);
        label_zjk->setObjectName(QString::fromUtf8("label_zjk"));
        label_zjk->setGeometry(QRect(800, 360, 54, 16));
        gs = new QLabel(LastWindow);
        gs->setObjectName(QString::fromUtf8("gs"));
        gs->setGeometry(QRect(357, 265, 411, 291));
        cq = new QLabel(LastWindow);
        cq->setObjectName(QString::fromUtf8("cq"));
        cq->setGeometry(QRect(596, 489, 185, 113));
        bj = new QLabel(LastWindow);
        bj->setObjectName(QString::fromUtf8("bj"));
        bj->setGeometry(QRect(830, 275, 121, 101));
        hb = new QLabel(LastWindow);
        hb->setObjectName(QString::fromUtf8("hb"));
        hb->setGeometry(QRect(793, 238, 171, 221));
        hn = new QLabel(LastWindow);
        hn->setObjectName(QString::fromUtf8("hn"));
        hn->setGeometry(QRect(727, 420, 121, 101));
        zj = new QLabel(LastWindow);
        zj->setObjectName(QString::fromUtf8("zj"));
        zj->setGeometry(QRect(878, 490, 181, 161));
        ah = new QLabel(LastWindow);
        ah->setObjectName(QString::fromUtf8("ah"));
        ah->setGeometry(QRect(775, 398, 151, 181));
        hlj = new QLabel(LastWindow);
        hlj->setObjectName(QString::fromUtf8("hlj"));
        hlj->setGeometry(QRect(859, -20, 411, 311));
        jl = new QLabel(LastWindow);
        jl->setObjectName(QString::fromUtf8("jl"));
        jl->setGeometry(QRect(937, 151, 251, 185));
        ln = new QLabel(LastWindow);
        ln->setObjectName(QString::fromUtf8("ln"));
        ln->setGeometry(QRect(890, 191, 201, 201));
        nmg = new QLabel(LastWindow);
        nmg->setObjectName(QString::fromUtf8("nmg"));
        nmg->setGeometry(QRect(470, 27, 921, 411));
        xj = new QLabel(LastWindow);
        xj->setObjectName(QString::fromUtf8("xj"));
        xj->setGeometry(QRect(9, 83, 491, 421));
        fj = new QLabel(LastWindow);
        fj->setObjectName(QString::fromUtf8("fj"));
        fj->setGeometry(QRect(803, 586, 141, 131));
        jx = new QLabel(LastWindow);
        jx->setObjectName(QString::fromUtf8("jx"));
        jx->setGeometry(QRect(770, 551, 171, 151));
        sc = new QLabel(LastWindow);
        sc->setObjectName(QString::fromUtf8("sc"));
        sc->setGeometry(QRect(470, 455, 221, 201));
        js = new QLabel(LastWindow);
        js->setObjectName(QString::fromUtf8("js"));
        js->setGeometry(QRect(823, 426, 151, 141));
        sd = new QLabel(LastWindow);
        sd->setObjectName(QString::fromUtf8("sd"));
        sd->setGeometry(QRect(797, 321, 181, 171));
        sh = new QLabel(LastWindow);
        sh->setObjectName(QString::fromUtf8("sh"));
        sh->setGeometry(QRect(930, 482, 121, 101));
        tj = new QLabel(LastWindow);
        tj->setObjectName(QString::fromUtf8("tj"));
        tj->setGeometry(QRect(837, 297, 161, 101));
        label_zz = new QLabel(LastWindow);
        label_zz->setObjectName(QString::fromUtf8("label_zz"));
        label_zz->setGeometry(QRect(770, 450, 54, 12));
        label_kf = new QLabel(LastWindow);
        label_kf->setObjectName(QString::fromUtf8("label_kf"));
        label_kf->setGeometry(QRect(810, 450, 51, 16));
        label_ly = new QLabel(LastWindow);
        label_ly->setObjectName(QString::fromUtf8("label_ly"));
        label_ly->setGeometry(QRect(740, 480, 54, 12));
        label_jn = new QLabel(LastWindow);
        label_jn->setObjectName(QString::fromUtf8("label_jn"));
        label_jn->setGeometry(QRect(820, 420, 51, 20));
        label_qd = new QLabel(LastWindow);
        label_qd->setObjectName(QString::fromUtf8("label_qd"));
        label_qd->setGeometry(QRect(900, 410, 54, 12));
        label_yt = new QLabel(LastWindow);
        label_yt->setObjectName(QString::fromUtf8("label_yt"));
        label_yt->setGeometry(QRect(920, 400, 54, 12));
        label_rz = new QLabel(LastWindow);
        label_rz->setObjectName(QString::fromUtf8("label_rz"));
        label_rz->setGeometry(QRect(870, 432, 51, 20));
        label_nc = new QLabel(LastWindow);
        label_nc->setObjectName(QString::fromUtf8("label_nc"));
        label_nc->setGeometry(QRect(790, 600, 51, 16));
        label_jj = new QLabel(LastWindow);
        label_jj->setObjectName(QString::fromUtf8("label_jj"));
        label_jj->setGeometry(QRect(780, 580, 61, 21));
        label_sr = new QLabel(LastWindow);
        label_sr->setObjectName(QString::fromUtf8("label_sr"));
        label_sr->setGeometry(QRect(838, 578, 61, 16));
        label_gz = new QLabel(LastWindow);
        label_gz->setObjectName(QString::fromUtf8("label_gz"));
        label_gz->setGeometry(QRect(790, 665, 61, 16));
        label_cd = new QLabel(LastWindow);
        label_cd->setObjectName(QString::fromUtf8("label_cd"));
        label_cd->setGeometry(QRect(545, 526, 61, 21));
        label_zg = new QLabel(LastWindow);
        label_zg->setObjectName(QString::fromUtf8("label_zg"));
        label_zg->setGeometry(QRect(565, 542, 51, 20));
        label_my = new QLabel(LastWindow);
        label_my->setObjectName(QString::fromUtf8("label_my"));
        label_my->setGeometry(QRect(565, 502, 51, 20));
        label_luzhou = new QLabel(LastWindow);
        label_luzhou->setObjectName(QString::fromUtf8("label_luzhou"));
        label_luzhou->setGeometry(QRect(590, 562, 51, 20));
        label_nj = new QLabel(LastWindow);
        label_nj->setObjectName(QString::fromUtf8("label_nj"));
        label_nj->setGeometry(QRect(865, 515, 51, 21));
        label_xz = new QLabel(LastWindow);
        label_xz->setObjectName(QString::fromUtf8("label_xz"));
        label_xz->setGeometry(QRect(860, 450, 51, 16));
        label_yz = new QLabel(LastWindow);
        label_yz->setObjectName(QString::fromUtf8("label_yz"));
        label_yz->setGeometry(QRect(880, 482, 51, 20));
        label_heb = new QLabel(LastWindow);
        label_heb->setObjectName(QString::fromUtf8("label_heb"));
        label_heb->setGeometry(QRect(1000, 100, 71, 16));
        label_cc = new QLabel(LastWindow);
        label_cc->setObjectName(QString::fromUtf8("label_cc"));
        label_cc->setGeometry(QRect(1020, 240, 61, 16));
        label_bx = new QLabel(LastWindow);
        label_bx->setObjectName(QString::fromUtf8("label_bx"));
        label_bx->setGeometry(QRect(950, 300, 54, 12));
        label_hhht = new QLabel(LastWindow);
        label_hhht->setObjectName(QString::fromUtf8("label_hhht"));
        label_hhht->setGeometry(QRect(700, 300, 131, 21));
        label_wlmq = new QLabel(LastWindow);
        label_wlmq->setObjectName(QString::fromUtf8("label_wlmq"));
        label_wlmq->setGeometry(QRect(200, 280, 141, 41));
        label_xm = new QLabel(LastWindow);
        label_xm->setObjectName(QString::fromUtf8("label_xm"));
        label_xm->setGeometry(QRect(845, 675, 61, 31));
        label_qz = new QLabel(LastWindow);
        label_qz->setObjectName(QString::fromUtf8("label_qz"));
        label_qz->setGeometry(QRect(850, 657, 51, 20));
        label_fz = new QLabel(LastWindow);
        label_fz->setObjectName(QString::fromUtf8("label_fz"));
        label_fz->setGeometry(QRect(860, 629, 51, 20));
        label_hz = new QLabel(LastWindow);
        label_hz->setObjectName(QString::fromUtf8("label_hz"));
        label_hz->setGeometry(QRect(878, 560, 51, 20));
        label_hf = new QLabel(LastWindow);
        label_hf->setObjectName(QString::fromUtf8("label_hf"));
        label_hf->setGeometry(QRect(850, 540, 51, 16));
        cityCount = new QLabel(LastWindow);
        cityCount->setObjectName(QString::fromUtf8("cityCount"));
        cityCount->setGeometry(QRect(430, 70, 391, 91));
        userRate = new QLabel(LastWindow);
        userRate->setObjectName(QString::fromUtf8("userRate"));
        userRate->setGeometry(QRect(430, 71, 371, 161));
        username = new QLabel(LastWindow);
        username->setObjectName(QString::fromUtf8("username"));
        username->setGeometry(QRect(430, 0, 371, 81));
        username->setAlignment(Qt::AlignCenter);
        count = new QLabel(LastWindow);
        count->setObjectName(QString::fromUtf8("count"));
        count->setGeometry(QRect(630, 75, 51, 91));
        count->setAlignment(Qt::AlignCenter);
        rate = new QLabel(LastWindow);
        rate->setObjectName(QString::fromUtf8("rate"));
        rate->setGeometry(QRect(572, 155, 90, 121));
        hb->raise();
        bj->raise();
        cq->raise();
        gs->raise();
        textBrowser->raise();
        label_cq->raise();
        label_bj->raise();
        label_xg->raise();
        label_sh->raise();
        label_tj->raise();
        label_am->raise();
        label_by->raise();
        label_dh->raise();
        label_ts->raise();
        label_sjz->raise();
        label_zjk->raise();
        label_lz->raise();
        hn->raise();
        zj->raise();
        ah->raise();
        hlj->raise();
        jl->raise();
        ln->raise();
        nmg->raise();
        xj->raise();
        fj->raise();
        jx->raise();
        sc->raise();
        js->raise();
        sd->raise();
        sh->raise();
        tj->raise();
        label_zz->raise();
        label_kf->raise();
        label_ly->raise();
        label_jn->raise();
        label_qd->raise();
        label_yt->raise();
        label_rz->raise();
        label_nc->raise();
        label_jj->raise();
        label_sr->raise();
        label_gz->raise();
        label_cd->raise();
        label_zg->raise();
        label_my->raise();
        label_luzhou->raise();
        label_nj->raise();
        label_xz->raise();
        label_yz->raise();
        label_heb->raise();
        label_cc->raise();
        label_bx->raise();
        label_hhht->raise();
        label_wlmq->raise();
        label_xm->raise();
        label_qz->raise();
        label_fz->raise();
        label_hz->raise();
        label_hf->raise();
        cityCount->raise();
        userRate->raise();
        username->raise();
        count->raise();
        rate->raise();

        retranslateUi(LastWindow);

        QMetaObject::connectSlotsByName(LastWindow);
    } // setupUi

    void retranslateUi(QDialog *LastWindow)
    {
        LastWindow->setWindowTitle(QCoreApplication::translate("LastWindow", "Dialog", nullptr));
        label_cq->setText(QString());
        label_bj->setText(QString());
        label_xg->setText(QString());
        label_sh->setText(QString());
        label_tj->setText(QString());
        label_lz->setText(QString());
        label_am->setText(QString());
        label_by->setText(QString());
        label_dh->setText(QString());
        label_ts->setText(QString());
        label_sjz->setText(QString());
        label_zjk->setText(QString());
        gs->setText(QString());
        cq->setText(QString());
        bj->setText(QString());
        hb->setText(QString());
        hn->setText(QString());
        zj->setText(QString());
        ah->setText(QString());
        hlj->setText(QString());
        jl->setText(QString());
        ln->setText(QString());
        nmg->setText(QString());
        xj->setText(QString());
        fj->setText(QString());
        jx->setText(QString());
        sc->setText(QString());
        js->setText(QString());
        sd->setText(QString());
        sh->setText(QString());
        tj->setText(QString());
        label_zz->setText(QString());
        label_kf->setText(QString());
        label_ly->setText(QString());
        label_jn->setText(QString());
        label_qd->setText(QString());
        label_yt->setText(QString());
        label_rz->setText(QString());
        label_nc->setText(QString());
        label_jj->setText(QString());
        label_sr->setText(QString());
        label_gz->setText(QString());
        label_cd->setText(QString());
        label_zg->setText(QString());
        label_my->setText(QString());
        label_luzhou->setText(QString());
        label_nj->setText(QString());
        label_xz->setText(QString());
        label_yz->setText(QString());
        label_heb->setText(QString());
        label_cc->setText(QString());
        label_bx->setText(QString());
        label_hhht->setText(QString());
        label_wlmq->setText(QString());
        label_xm->setText(QString());
        label_qz->setText(QString());
        label_fz->setText(QString());
        label_hz->setText(QString());
        label_hf->setText(QString());
        cityCount->setText(QString());
        userRate->setText(QString());
        username->setText(QString());
        count->setText(QString());
        rate->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class LastWindow: public Ui_LastWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_LASTWINDOW_H
